#8888888b.   .d8888b.   .d88888b.   .d8888b. 88888888888     d8888  d8888888888P
#888   Y88b d88P  Y88b d88P" "Y88b d88P  Y88b    888        d88888  88888888888P
#888    888 888    888 888     888 Y88b.         888       d88P888        d888P
#888   d88P 888        888     888  "Y888b.      888      d88P 888       d888P
#8888888P"  888        888     888     "Y88b.    888     d88P  888      d888P
#888 T88b   888    888 888     888       "888    888    d88P   888     d888P
#888  T88b  Y88b  d88P Y88b. .d88P Y88b  d88P    888   d8888888888    d888P
#888   T88b  "Y8888P"   "Y88888P"   "Y8888P"     888  d88P     888   d888P
---


version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=002
      - serverIP=ipv4_address
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      
    restart: unless-stopped      
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 

    volumes:
      - server:/app/server
      - config:/app/configs
      - /media:/media
      - /var/log/tdarr:/app/logs
      - /temp:/temp
      
    networks:
      my_network:  # Created by docker with macvlan driver
        ipv4_address: ipv4_address # IP in your network used to access to the service 
    
networks:
  my_network:
    external: true  

# You will need to have docker local-persist plugin installed
volumes:
  server:
    driver: local-persist
    driver_opts:
      mountpoint: /home/user/docker/tdarr/server

  config:
    driver: local-persist
    driver_opts:
      mountpoint: /home/user/docker/tdarr/config