#8888888b.   .d8888b.   .d88888b.   .d8888b. 88888888888     d8888  d8888888888P
#888   Y88b d88P  Y88b d88P" "Y88b d88P  Y88b    888        d88888  88888888888P
#888    888 888    888 888     888 Y88b.         888       d88P888        d888P
#888   d88P 888        888     888  "Y888b.      888      d88P 888       d888P
#8888888P"  888        888     888     "Y88b.    888     d88P  888      d888P
#888 T88b   888    888 888     888       "888    888    d88P   888     d888P
#888  T88b  Y88b  d88P Y88b. .d88P Y88b  d88P    888   d8888888888    d888P
#888   T88b  "Y8888P"   "Y88888P"   "Y8888P"     888  d88P     888   d888P

version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
      
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
      
    restart: unless-stopped

# You will need to have local-persist plugin installed
volumes:
    portainer:
        name: portainer
        driver: local-persist
        driver_opts:
            mountpoint: "/home/user/docker/portainer/data" # Path where you going to safe the internal /data directory 
