#8888888b.   .d8888b.   .d88888b.   .d8888b. 88888888888     d8888  d8888888888P
#888   Y88b d88P  Y88b d88P" "Y88b d88P  Y88b    888        d88888  88888888888P
#888    888 888    888 888     888 Y88b.         888       d88P888        d888P
#888   d88P 888        888     888  "Y888b.      888      d88P 888       d888P
#8888888P"  888        888     888     "Y88b.    888     d88P  888      d888P
#888 T88b   888    888 888     888       "888    888    d88P   888     d888P
#888  T88b  Y88b  d88P Y88b. .d88P Y88b  d88P    888   d8888888888    d888P
#888   T88b  "Y8888P"   "Y88888P"   "Y8888P"     888  d88P     888   d888P
---

version: '3'
services:
  docker-socket:
    container_name: docker-socket
    image: tecnativa/docker-socket-proxy
    restart: always

    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    environment:
      - LOG_LEVEL=info
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
