#8888888b.   .d8888b.   .d88888b.   .d8888b. 88888888888     d8888  d8888888888P
#888   Y88b d88P  Y88b d88P" "Y88b d88P  Y88b    888        d88888  88888888888P
#888    888 888    888 888     888 Y88b.         888       d88P888        d888P
#888   d88P 888        888     888  "Y888b.      888      d88P 888       d888P
#8888888P"  888        888     888     "Y88b.    888     d88P  888      d888P
#888 T88b   888    888 888     888       "888    888    d88P   888     d888P
#888  T88b  Y88b  d88P Y88b. .d88P Y88b  d88P    888   d8888888888    d888P
#888   T88b  "Y8888P"   "Y88888P"   "Y8888P"     888  d88P     888   d888P
---

version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - sonarr:/config
      - /media/tv:/tv
      - /media/downloads/tv:/downloads #optional

    networks:
      my_network:  # Created by docker with macvlan driver
        ipv4_address: 192.168.xxx.xxx # IP in your network used to access to the service 
    
networks:
  my_network:
    external: true
    
# You will need to have local-persist plugin installed
volumes:
    sonarr:
        name: sonarr
        driver: local-persist
        driver_opts:
            mountpoint: "/home/user/docker/sonarr/data" # Path where you going to safe the internal /data directory 
