#8888888b.   .d8888b.   .d88888b.   .d8888b. 88888888888     d8888  d8888888888P
#888   Y88b d88P  Y88b d88P" "Y88b d88P  Y88b    888        d88888  88888888888P
#888    888 888    888 888     888 Y88b.         888       d88P888        d888P
#888   d88P 888        888     888  "Y888b.      888      d88P 888       d888P
#8888888P"  888        888     888     "Y88b.    888     d88P  888      d888P
#888 T88b   888    888 888     888       "888    888    d88P   888     d888P
#888  T88b  Y88b  d88P Y88b. .d88P Y88b  d88P    888   d8888888888    d888P
#888   T88b  "Y8888P"   "Y88888P"   "Y8888P"     888  d88P     888   d888P
---

version: '3'

services:
  vaultwarden:
    container_name: bitwarden  
    image: vaultwarden/server:latest
    restart: unless-stopped

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: false
      INVITATIONS_ALLOWED: false
      DATABASE_URL: postgresql://vaultwarden:vaultwarden@ipv4_address:5432/vaultwarden
      ADMIN_TOKEN: "biuyyt8-d-ddeeee-eeewqe-fgerhrtjh-rewef-day"
      DOMAIN: "https://my-domain.com"
      ENABLE_DB_WAL: false
    volumes:
      - bitwarden:/data 
    
    networks:
      my_network:  # Created by docker with macvlan driver
        ipv4_address: ipv4_address # IP in your network used to access to the service 

networks:
  services:
    external: true

    
volumes:
    bitwarden:
        name: bitwarden
        driver: local-persist # local-persist plugin installed manually in the system
        driver_opts:
            mountpoint: "/path_to/local_folder/data"